### ISSUE TITLE
How can I make my views fill the whole cell?

### ISSUE THREAD

**Issue by Sweeper777** [mihaimihaila/GridLayout#1]
By setting constraints on the grid view, I can make the cells of the grid change size. However, in all of the examples shown, only views with a fixed width and height are used. How can I make it so that my views automatically resize to fill almost the whole cell, leaving a small margin?

**Comment by mihaimihaila** [comment]
You can use the `stretch` horizontal and vertical alignment.

Here is a sample:

```swift
let rectangle = UIView(frame: .zero)
rectangle.translatesAutoresizingMaskIntoConstraints = false
rectangle.backgroundColor = .blue

let grid = UIView.gridLayoutView(items: [[GridItem(rectangle, 
                                                   horizontalAlignment: .stretch, 
                                                   verticalAlignment: .stretch, 
                                                   margin: UIEdgeInsets(top: 20, left: 10, bottom: 30, right: 50))]],
                                rows: [.fill],
                                columns: [.fill],
                                width: 90,
                                height: 90)
```

which will produce the following output:
![11](https://user-images.githubusercontent.com/1834531/65625183-a02a6980-dfcb-11e9-8b6c-b45665c21be2.png)

Thank you for the question, I added the answer to our documentation https://github.com/mihaimihaila/GridLayout/blob/master/docs/fill.md and also added a unit test for the scenario you were interested in.

Thank you for trying out **GridLayout**!

**Comment by Sweeper777** [comment]
Thank you!
