### ISSUE TITLE
Derive height from content

### ISSUE THREAD

**Issue by Bharath2r** [mihaimihaila/GridLayout#2]
Is there a possibility to have the grid derive its height from content in sub views. This is extremely useful when rendering dynamic views in table/collection view

**Comment by mihaimihaila** [comment]
Yes you can! Just use `stretch` vertical or horizontal alignment. I added a sample to our documentation: https://github.com/mihaimihaila/GridLayout/blob/master/docs/fill.md.

Thank you for trying out **GridLayout**!
